name: lfdi
description: Last.fm Discord Integrator

publish_to: 'none' 
version: 1.0.0-beta.5

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dart_discord_rpc: ^0.0.2
  flutter_riverpod: ^1.0.3
  system_theme: ^2.0.0
  flutter_acrylic: ^1.0.0+2
  http: ^0.13.4
  url_launcher: ^6.1.0
  package_info_plus: ^1.4.2
  tray_manager: ^0.1.4
  fluent_ui:
    git:
      url: https://github.com/tangenx/fluent_ui.git
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  web_socket_channel: ^2.2.0
  spotify: ^0.7.0
  logger: ^1.1.0
  bitsdojo_window:
    git: 
      url: https://github.com/alexmercerind/bitsdojo_window.git
      path: bitsdojo_window
      ref: 5e6ddd4b58bb357b23541181b4188ce5892ba7a3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  msix: ^3.5.1
  hive_generator: ^1.1.2
  build_runner: ^2.1.10

dependency_overrides:
  bitsdojo_window_windows:
    git:
      url: https://github.com/alexmercerind/bitsdojo_window.git
      path: bitsdojo_window_windows
      ref: 5e6ddd4b58bb357b23541181b4188ce5892ba7a3

flutter:
  uses-material-design: false

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: LFDI
      fonts:
      - asset: assets/fonts/LFDI.ttf