name: lfdi
description: Last.fm Discord Integrator

publish_to: 'none' 
version: 1.0.0-beta.8

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dart_discord_rpc:
    git: 
      url: https://github.com/alexmercerind/dart_discord_rpc.git
      ref: 5760594e9a8417683fa969fe48c1e8593928fd35
  flutter_riverpod: ^1.0.3
  system_theme: ^2.0.0
  flutter_acrylic: ^1.0.0+2
  http: ^0.13.4
  url_launcher: ^6.1.0
  package_info_plus: ^1.4.2
  tray_manager:
    git:
      url: https://github.com/leanflutter/tray_manager.git
      ref: f075f39e978e7c664e81916d0c8da0b4955906cd
  fluent_ui:
    git:
      url: https://github.com/tangenx/fluent_ui.git
      ref: 87525a1588c34399239644b35bda3bae6490685f
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  web_socket_channel: ^2.2.0
  spotify: #^0.7.0
    git: 
      url: https://github.com/tangenx/spotify-dart.git
      ref: 57e3fb38b615d49f2056d638ab8d094bde84c21d
  logger: ^1.1.0
  bitsdojo_window:
    git: 
      url: https://github.com/tangenx/bitsdojo_window.git
      path: bitsdojo_window
      ref: 21fc5740e614fefa90f627bafcc22093382f24a7
      # url: https://github.com/abutcher-gh/bitsdojo_window.git
      # path: bitsdojo_window
      # ref: b823ae5b9f2f82635067add7eadfc32d9054bc2b
      # url: https://github.com/alexmercerind/bitsdojo_window.git
      # path: bitsdojo_window
      # ref: b5e9648081f73c05df612cd5b958d8e6cab77898
  launch_at_startup: ^0.1.7
  window_manager: ^0.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.10

dependency_overrides:
  bitsdojo_window_platform_interface:
    git:
      url: https://github.com/tangenx/bitsdojo_window.git
      path: bitsdojo_window_platform_interface
      ref: 21fc5740e614fefa90f627bafcc22093382f24a7
  bitsdojo_window_windows:
    git:
      url: https://github.com/tangenx/bitsdojo_window.git
      path: bitsdojo_window_windows
      ref: 21fc5740e614fefa90f627bafcc22093382f24a7
      # url: https://github.com/abutcher-gh/bitsdojo_window.git
      # path: bitsdojo_window_windows
      # ref: b823ae5b9f2f82635067add7eadfc32d9054bc2b
      # url: https://github.com/alexmercerind/bitsdojo_window.git
      # path: bitsdojo_window_windows
      # ref: b5e9648081f73c05df612cd5b958d8e6cab77898
  bitsdojo_window_linux:
    git:
      url: https://github.com/tangenx/bitsdojo_window.git
      path: bitsdojo_window_linux
      ref: 21fc5740e614fefa90f627bafcc22093382f24a7
  bitsdojo_window_macos:
    git:
      url: https://github.com/tangenx/bitsdojo_window.git
      path: bitsdojo_window_macos
      ref: 21fc5740e614fefa90f627bafcc22093382f24a7

flutter:
  uses-material-design: false

  assets:
    - assets/images/

  fonts:
    - family: LFDI
      fonts:
      - asset: assets/fonts/LFDI.ttf

msix_config:
  display_name: Last.fm Discord Integrator
  publisher_display_name: tangenx
  identity_name: tangenx.lfdi
  msix_version: 1.0.0.0
  logo_path: "D:\\Code Projects\\lfdi\\assets\\images\\logo_big.png"
  capabilities: internetClient
