name: lfdi
description: Last.fm Discord Integrator

publish_to: 'none' 
version: 1.0.0-beta.3

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dart_discord_rpc: ^0.0.2
  flutter_riverpod: ^1.0.3
  shared_preferences: ^2.0.13
  system_theme: ^2.0.0
  flutter_acrylic: ^1.0.0+2
  window_manager: ^0.2.2
  http: ^0.13.4
  url_launcher: ^6.1.0
  package_info_plus: ^1.4.2
  tray_manager: ^0.1.4
  fluent_ui:
    git:
      url: https://github.com/tangenx/fluent_ui.git



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  msix: ^3.5.1

flutter:
  uses-material-design: false

  assets:
    - assets/images/
